### PR TITLE
Switch your Desktop Enviroment

### PR DESCRIPTION
**Pull request by kylerschin**

### CODE REVIEW

**Comment by kylerschin** [comment]
@cassidyjames can plz have merge?

**Comment by cassidyjames** [comment]
I'm gonna leave this up to @ryanleesipes to decide if we want desktop environment docs here or not. Assigning for review. Thanks again for the contribution!

**Comment by Xeboc** [comment]
Much of this article is already here:

http://support.system76.com/articles/desktop-environment/

**Comment by kylerschin** [comment]
LOL

**Comment by kylerschin** [comment]
@Xeboc this actually hurts... Can we replicate that?

**Pull request closed without merging**
